'use strict';
const vehicles=[
 {name:'Motorcycle',tag:'Tiny, nimble, a little twitchy',color:'#e8b958',w:14,h:30,max:155,acc:47,brake:94,steer:960,grip:8.5,stats:[5,4,3,5]},
 {name:'Hatchback',tag:'Your happy little all-rounder',color:'#e78a61',w:25,h:39,max:142,acc:34,brake:83,steer:810,grip:9,stats:[4,3,4,4]},
 {name:'Family wagon',tag:'Smooth moves, room for everyone',color:'#88af9e',w:28,h:49,max:138,acc:27,brake:70,steer:660,grip:6.3,stats:[3,2,3,3]},
 {name:'Sports car',tag:'Quick off the mark, hugs the road',color:'#cf645b',w:27,h:39,max:183,acc:58,brake:105,steer:1070,grip:10,stats:[5,5,5,3]},
 {name:'SUV',label:'Land Cruiser',tag:'Boxy, trusty, ready for the long way',color:'#c9b681',w:33,h:47,max:147,acc:30,brake:65,steer:600,grip:5.5,stats:[2,3,2,2]}
];
const $=id=>document.getElementById(id),canvas=$('game');let selected=1,mode='ready',keys={},traffic=[],particles=[],elapsed=0,distance=0,speed=0,x=348,vx=0,scroll=0,spawnIn=1.3,near=0,noticeTime=0,last=0,best=0,sound=true,lives=3,invincible=0,animals=[],animalIn=10,junctions=[],crossTraffic=[],nextJunction=300,densityStep=0,nextBreakdown=220,police=[],chaseTime=0,tailTime=0;
try{best=Number(localStorage.getItem('littleLaneBest'))||0}catch{}$('best').innerHTML=String(Math.floor(best)).padStart(4,'0')+' <small>m</small>';
for(const v of vehicles){v.max=Math.round(v.max*1.55);v.acc*=1.65;v.brake*=1.7;}
const truck={name:'Truck',color:'#d7a359',w:38,h:122};
function densityMultiplier(m=distance){return 4*Math.pow(1.1,Math.floor(m/500))}
const lanes=[132,204,276,348],py=535;

let routeSeed=17;
function roadTarget(at){const block=Math.max(0,Math.floor(at/500)),group=Math.floor(block/5);const hash=((Math.imul(group+1,1664525)+routeSeed*1013904223)>>>0);const slot=group===0?2:hash%5;if(block%5!==slot)return 4;return (hash>>>8)%2?2:6;}
function roadAt(at){const target=roadTarget(at),offset=((at%500)+500)%500;const ramp=Math.max(0,Math.min(1,offset/65,(500-offset)/65));const ease=ramp*ramp*(3-2*ramp);const width=284+(target-4)*72*ease;const count=width<215?2:width>355?6:4;const spacing=width/count;return {count,width,left:240-width/2,right:240+width/2,centers:Array.from({length:count},(_,i)=>240-width/2+spacing*(i+.5))};}
function roadFor(t){return roadAt(distance+(py-t.y)/8.64)}
function fitTrafficToRoad(t,dt){const r=roadFor(t),old=t.roadCount??4;if(old!==r.count){const rank=t.oncoming?old/2-1-t.lane:t.lane-old/2;const nextRank=Math.max(0,Math.min(r.count/2-1,rank));t.lane=t.oncoming?r.count/2-1-nextRank:r.count/2+nextRank;t.target=t.lane;t.turning=0;t.warning=0;t.roadMerge=true;t.roadCount=r.count;}
 if(!t.turning&&!(t.warning>0)){const target=r.centers[t.lane];if(Number.isFinite(target)){const delta=target-t.x;t.mergeSide=Math.sign(delta);t.x+=delta*Math.min(1,dt*2);t.roadMerge=Math.abs(delta)>3;}}t.x=Math.max(r.left+t.v.w/2,Math.min(r.right-t.v.w/2,t.x));
}

function car(g,v,cx,cy,angle=0,reverse=false){if(v.name==='SUV'){g.save();g.translate(cx,cy);g.fillStyle='#283c3525';g.fillRect(-26,14,53,4);g.fillStyle=v.color;g.fillRect(-26,-5,50,18);g.fillRect(-9,-19,32,26);g.fillStyle='#35515c';g.fillRect(-6,-16,11,12);g.fillRect(8,-16,11,12);g.fillStyle='#f0e8d0';g.fillRect(-11,-22,36,4);g.fillStyle='#48534a';g.fillRect(-10,-25,35,2);g.fillRect(-7,-25,2,5);g.fillRect(20,-25,2,5);g.fillStyle='#424d45';g.fillRect(-27,9,53,4);g.fillRect(24,-7,5,18);g.fillStyle='#ffefbb';g.fillRect(-27,-3,3,6);for(const xx of [-17,16]){g.fillStyle='#29343a';g.beginPath();g.arc(xx,12,7,0,Math.PI*2);g.fill();g.fillStyle='#c1c2ad';g.beginPath();g.arc(xx,12,3,0,Math.PI*2);g.fill()}g.fillStyle='#827b61';g.fillRect(5,-3,1,13);g.fillRect(10,0,5,2);g.restore();return;}g.save();g.translate(Math.round(cx),Math.round(cy));g.rotate(angle+(reverse?Math.PI:0));const w=v.w,h=v.h;g.fillStyle='#283c3540';g.fillRect(-w/2+4,-h/2+5,w+2,h);g.fillStyle='#293c3b';g.fillRect(-w/2-3,-h/2+6,5,9);g.fillRect(w/2-2,-h/2+6,5,9);g.fillRect(-w/2-3,h/2-14,5,9);g.fillRect(w/2-2,h/2-14,5,9);g.fillStyle=v.color;g.fillRect(-w/2,-h/2+3,w,h-6);g.fillRect(-w/2+3,-h/2,w-6,h);if(v.name==='Motorcycle'){g.fillStyle='#34484b';g.fillRect(-5,-7,10,13);g.fillStyle='#fff0c2';g.fillRect(-5,-9,10,8)}else{g.fillStyle='#384e50';g.fillRect(-w/2+4,-h/2+10,w-8,9);g.fillRect(-w/2+4,h/2-13,w-8,6);g.fillStyle='#ffffff35';g.fillRect(-w/2+3,-h/2+2,3,h-6);g.fillStyle='#f9e7ad';g.fillRect(-w/2+2,-h/2,6,3);g.fillRect(w/2-8,-h/2,6,3)}g.fillStyle='#c35147';g.fillRect(-w/2+2,h/2-3,4,3);g.fillRect(w/2-6,h/2-3,4,3);g.restore()}
function garage(){ $('garage').innerHTML='';vehicles.forEach((v,i)=>{const b=document.createElement('button');b.className='ride'+(i===selected?' selected':'');b.setAttribute('aria-pressed',i===selected);b.innerHTML='<canvas width="64" height="52"></canvas><div><strong>'+(v.label||v.name)+'</strong><small>'+v.tag+'</small></div><span class="number">0'+(i+1)+'</span>';car(b.querySelector('canvas').getContext('2d'),v,32,26,Math.PI/2);b.onclick=()=>{selected=i;garage()};b.disabled=mode==='playing'||mode==='paused';$('garage').appendChild(b)});$('specs').innerHTML=['STEERING','ACCELERATION','BRAKING','COMPACTNESS'].map((s,i)=>'<div>'+s+'<div class="meter">'+[1,2,3,4,5].map(n=>'<i class="'+(n<=vehicles[selected].stats[i]?'on':'')+'"></i>').join('')+'</div></div>').join('')}
function beep(freq,dur=.08){if(sound)window.drivingAudio?.beep(freq,dur)}
function announce(t){$('notice').textContent=t;noticeTime=2.5}
function start(){window.drivingAudio?.unlock();mode='playing';elapsed=distance=scroll=near=0;lives=3;invincible=0;animals=[];animalIn=10;updateLives();junctions=[];crossTraffic=[];nextJunction=300;densityStep=0;nextBreakdown=220;police=[];chaseTime=0;tailTime=0;routeSeed=Math.floor(Math.random()*1e6);traffic=[];particles=[];speed=135;x=348;vx=0;spawnIn=1.4;keys={};$('overlay').classList.add('hidden');$('status').textContent='ON THE ROAD';$('pause').textContent='Ⅱ';garage();announce('Happy travels!  ↑ gas · ↓ brake');beep(440)}
function pause(){window.drivingAudio?.unlock();if(mode==='playing'){mode='paused';show('A little pit stop.','Stretch your legs. The road can wait.','KEEP ROLLING');$('status').textContent='TAKING A BREAK';$('pause').textContent='▶'}else if(mode==='paused'){mode='playing';keys={};$('overlay').classList.add('hidden');$('status').textContent='ON THE ROAD';$('pause').textContent='Ⅱ'}}
function show(title,text,button){$('overlayTitle').innerHTML=title;$('overlayText').innerHTML=text;$('start').innerHTML=button+' <span>→</span>';$('overlay').classList.remove('hidden')}
function updateLives(){$('lives').textContent='♥'.repeat(lives)+'♡'.repeat(3-lives)}
function crash(){if(mode!=='playing'||invincible>0)return;window.drivingAudio?.event('crash');lives--;updateLives();if(lives>0){invincible=2.5;speed=Math.max(30,speed*.6);announce('Oops! '+lives+' lives left — keep going');return}mode='over';for(let i=0;i<28;i++)particles.push({x,y:py,vx:(Math.random()-.5)*160,vy:(Math.random()-.5)*180,life:1});if(distance>best){best=distance;try{localStorage.setItem('littleLaneBest',String(best))}catch{}}$('best').innerHTML=Math.floor(best).toString().padStart(4,'0')+' <small>m</small>';show('Oh, bumper.','You travelled <b>'+Math.floor(distance)+' metres</b>.<br>'+near+' close calls. Plenty more road ahead.','ONE MORE RUN');$('status').textContent='END OF THE ROAD';garage()}
function spawn(){const r=roadAt(distance+(py+1850)/8.64),free=Math.floor(Math.random()*r.count);const count=r.count===2?1:Math.random()<.25?2:1;const options=Array.from({length:r.count},(_,i)=>i).filter(i=>i!==free).sort(()=>Math.random()-.5);for(let k=0;k<count;k++){const lane=options[k],oncoming=lane<r.count/2;const v=Math.random()<.25?truck:vehicles[1+Math.floor(Math.random()*4)];const yy=-1850-k*220;if(traffic.some(t=>t.lane===lane&&Math.abs(t.y-yy)<190))continue;const cruise=(oncoming?-1:1)*(v.name==='Truck'?65+Math.random()*15:85+Math.random()*25);traffic.push({x:r.centers[lane]+(Math.random()-.5)*8,roadCount:r.count,y:yy,lane,target:lane,v:{...v,color:['#e8c878','#bed3be','#df9989','#8aaebc'][Math.floor(Math.random()*4)]},speed:cruise,cruise,oncoming,cooldown:4+Math.random()*7,slowTimer:0,turning:0,warning:0,passed:false})}}
function signalPhase(time,index){const t=(time+index*4)%24;return t<10?'green':t<13?'amber':'red'}
// The 70% roll creates a timed crossing vehicle, never immunity or invisible damage.
function prepareRedThreat(j){if(j.riskPrepared)return;j.riskPrepared=true;j.redCollisionRisk=Math.random()<.7;if(!j.redCollisionRisk)return;const dir=x>=240?-1:1;crossTraffic.push({x:dir===1?35:445,y:j.y+dir*34,j,dir,v:{...vehicles[1],color:'#dca66c'},riskVehicle:true,waiting:true,moveSpeed:170});}
function startPoliceChase(){chaseTime=22;if(police.length)return;tailTime=0;police.push({x,y:py+110,v:{...vehicles[3],name:'Police',color:'#edf0e3'},speed:180,warning:0,turning:0,oncoming:false});announce('Police pursuit! Keep moving to lose them.');}
function redViolation(j){window.drivingAudio?.event('red');j.ranRed=true;j.policeRoll=Math.random()<.3;if(j.policeRoll)startPoliceChase();else announce('Red light — watch for crossing traffic!');}
function updatePolice(dt){if(mode!=='playing')return;if(!police.length){tailTime=0;$('pursuit').textContent='';return;}chaseTime-=dt;const p=police[0],before=p.x;p.x+=(x-p.x)*Math.min(1,dt*1.8);const at=distance-(p.y-py)/8.64;if(medianSegments(at-3,at+3).length&&Math.min(before,p.x)<263&&Math.max(before,p.x)>217)p.x=before<240?217:263;
 p.y=Math.max(py+54,p.y+(speed-180)*1.1*dt);if(speed>190)chaseTime-=dt*1.5;
 const onTail=p.y<=py+85&&Math.abs(p.x-x)<30&&invincible<=0;
 tailTime=onTail?tailTime+dt:0;
 if(tailTime>=3){crash();tailTime=0;police=[];chaseTime=0;if(mode==='playing')announce('Busted! One life lost — pursuit cleared.');}
 else if(chaseTime<=0||p.y>880){police=[];tailTime=0;announce('You lost the pursuit!');}
 $('pursuit').textContent=police.length?(onTail?'🚨 ON YOUR TAIL · '+Math.max(0,3-tailTime).toFixed(1)+'s TO BUST':'🚨 POLICE PURSUIT · '+Math.ceil(chaseTime)+'s'):'';}

function updateJunctions(dt){
 while(nextJunction-distance<180){junctions.push({at:nextJunction,index:Math.round(nextJunction/400),y:0,phase:'green',redCycle:-1,checked:false});nextJunction+=400;}
 for(const j of junctions){const previous=j.y;const stopThreshold=py-vehicles[selected].h/2-105;j.y=py+(distance-j.at)*8.64;j.phase=signalPhase(elapsed,j.index);if(j.phase!=='red'&&crossTraffic.some(t=>t.j===j&&t.x>98-t.v.h/2&&t.x<382+t.v.h/2))j.phase='red';const cycle=Math.floor((elapsed+j.index*4)/24),phaseTime=(elapsed+j.index*4)%24;
 if(j.y>-1600&&j.y<py-100){$('junction').textContent=(j.phase==='red'?'🔴 STOP':j.phase==='amber'?'🟠 BRAKE':'🟢 GO')+' · '+Math.max(0,Math.round(j.at-distance))+' m';}
 if(!j.checked&&j.y>-1650&&!j.riskPrepared)prepareRedThreat(j);
 if(j.phase==='red'&&phaseTime>=13&&phaseTime<14.2&&j.redCycle!==cycle&&j.y>-1900&&j.y<800){j.redCycle=cycle;for(const dir of [-1,1])crossTraffic.push({x:dir===1?-90:570,y:j.y+dir*34,j,dir,v:{...(dir===1?truck:vehicles[2]),color:dir===1?'#dfaf67':'#92b7ba'},passed:false});}
 if(!j.checked&&j.y>=stopThreshold&&previous<stopThreshold){j.checked=true;if(j.phase==='red'){redViolation(j)}}
 }
 for(const t of crossTraffic){t.y=t.j.y+t.dir*34;if(t.riskVehicle&&t.waiting){const eta=(py-t.y)/Math.max(1,speed*2.4);const crossingTime=Math.abs(x-t.x)/170;if(t.j.phase==='red'&&speed>15&&eta>0&&eta<=crossingTime+.15){t.waiting=false;t.moveSpeed=Math.min(300,Math.max(90,Math.abs(x-t.x)/Math.max(.15,eta)));}else{continue;}}t.x+=t.dir*(t.moveSpeed??(t.v.name==='Truck'?90:170))*dt;const v=vehicles[selected];if(Math.abs(t.x-x)<(v.w+t.v.h)/2-4&&Math.abs(t.y-py)<(v.h+t.v.w)/2-4)crash()}
 crossTraffic=crossTraffic.filter(t=>t.x>-210&&t.x<690&&t.y<900&&!(t.waiting&&t.j.checked&&!t.j.ranRed));
 junctions=junctions.filter(j=>j.y<1150);
 if(!junctions.some(j=>j.y>-1600&&j.y<py-100))$('junction').textContent='OPEN ROAD';
}
function trafficSpeed(t,dt){let target=t.breakdown?0:(t.cruise??t.speed)*(t.slowTimer>0?.32:1);for(const j of junctions){if(j.phase==='green')continue;const gap=t.oncoming?j.y-110-t.y:t.y-j.y-110;if(gap>=0&&gap<800){const allowed=Math.sqrt(2*100*gap/2.4);target=t.oncoming?-Math.min(Math.abs(target),allowed):Math.min(target,allowed)}}
 for(const o of traffic){if(o===t||o.oncoming!==t.oncoming||Math.abs(o.x-t.x)>40)continue;const gap=(t.oncoming?o.y-t.y:t.y-o.y)-(t.v.h+o.v.h)/2-32;if(gap>=-15&&gap<170){const allowed=Math.max(0,Math.abs(o.speed)+gap*.35);target=t.oncoming?-Math.min(Math.abs(target),allowed):Math.min(target,allowed)}}
 if(!t.oncoming&&Math.abs(t.x-x)<(t.v.w+vehicles[selected].w)/2+8&&t.y>py){const gap=t.y-py-(t.v.h+vehicles[selected].h)/2-28;if(gap<230)target=Math.min(target,Math.max(0,speed+gap*.4));}
 t.braking=Math.abs(target)<Math.abs(t.speed)-4||t.slowTimer>0;t.speed+=(target-t.speed)*Math.min(1,dt*7);
}
function update(dt){if(mode==='playing'){elapsed+=dt;invincible=Math.max(0,invincible-dt);const v=vehicles[selected],gas=keys.ArrowUp||keys.w,brake=keys.ArrowDown||keys.s,steer=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0);speed+= (brake?-v.brake:gas?v.acc:(155-speed)*.8)*dt;speed=Math.max(0,Math.min(v.max,speed));vx+=(steer*v.steer*(.58+speed/240)-vx*v.grip)*dt;const previousX=x;x+=vx*dt;const road=roadAt(distance),lo=road.left+v.w/2,hi=road.right-v.w/2;if(x<lo||x>hi){x=Math.max(lo,Math.min(hi,x));vx=0;speed=Math.max(0,speed-45*dt)}distance+=speed/3.6*dt;scroll+=speed*2.4*dt;
const step=Math.floor(distance/500);if(step!==densityStep){densityStep=step;announce(step*500+' m! Traffic ×'+densityMultiplier().toFixed(2));} $('density').textContent='TRAFFIC ×'+densityMultiplier().toFixed(2);
enforceMedian(previousX);updateBreakdowns();updateJunctions(dt);updatePolice(dt);spawnIn-=dt*densityMultiplier();if(spawnIn<=0){spawn();spawnIn+=2.05+Math.random()*.3;}
for(const t of traffic){trafficSpeed(t,dt);t.y+=(speed-t.speed)*2.4*dt;
fitTrafficToRoad(t,dt);updateDriver(t,dt);
const dx=Math.abs(t.x-x),dy=Math.abs(t.y-py);if(dx<(v.w+t.v.w)/2-4&&dy<(v.h+t.v.h)/2-5){crash();break}if(!t.passed&&t.y>py+45){t.passed=true;if(dx<55){near++;beep(720,.04);announce('Nice squeeze!  '+near+' close call'+(near===1?'':'s'))}}}
updateAnimals(dt);traffic=traffic.filter(t=>t.y<750&&t.y>-3000);$('distance').innerHTML=Math.floor(distance).toString().padStart(4,'0')+' <small>m</small>';$('speed').textContent=Math.round(speed);$('stage').textContent=elapsed<25?'SUNDAY DRIVE':elapsed<60?'PICKING UP':elapsed<110?'RUSH HOUR':'THE LONG HAUL';}
if(mode!=='paused')for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';}
function frame(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(frame)}
$('start').onclick=()=>mode==='paused'?pause():start();$('pause').onclick=pause;$('sound').onclick=()=>{sound=!sound;window.drivingAudio?.setEnabled(sound);$('sound').textContent=sound?'SFX ON':'SFX OFF';beep(520)};
window.addEventListener('keydown',e=>{if(e.target.closest?.('.mixtapes, #mobile-drawer, #mobile-menu'))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();const k=e.key.toLowerCase();keys[e.key.startsWith('Arrow')?e.key:k]=true;if(e.repeat)return;if(e.key===' '||k==='p'||e.key==='Escape'){if(mode==='playing'||mode==='paused')pause();else if(e.key===' ')start()}if(k==='r')start()});window.addEventListener('keyup',e=>{keys[e.key.startsWith('Arrow')?e.key:e.key.toLowerCase()]=false});window.addEventListener('blur',()=>{keys={};if(mode==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause()});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys[b.dataset.key]=false});garage();requestAnimationFrame(frame);

function updateAnimals(dt){animalIn-=dt;if(animalIn<=0&&!junctions.some(j=>j.y>-1600&&j.y<850)){const fromLeft=Math.random()<.5,r=roadAt(distance+(py+100)/8.64);animals.push({x:fromLeft?r.left-32:r.right+32,y:-100,dir:fromLeft?1:-1,type:Math.random()<.5?'cat':'dog',wait:1.5,done:false});animalIn=Math.max(7,17-elapsed*.045)+Math.random()*4;announce('Pet crossing ahead — slow down!')}
for(const a of animals){a.y+=speed*1.45*dt;if(a.wait>0)a.wait-=dt;else a.x+=a.dir*(36+Math.min(18,elapsed*.08))*dt;const v=vehicles[selected];if(!a.done&&Math.abs(a.x-x)<v.w/2+8&&Math.abs(a.y-py)<v.h/2+9){a.done=true;crash()}if(!a.done&&a.y>py+40){a.done=true;near+=2;announce('Safe crossing! Nicely avoided.');beep(660,.08)}}animals=animals.filter(a=>a.y<720&&a.x>-120&&a.x<600)}

function draw(){window.drivingAudio?.update({selected,mode,speed,vx,police,gas:!!(keys.ArrowUp||keys.w),braking:!!(keys.ArrowDown||keys.s)});if(window.renderLane)window.renderLane({vehicles,selected,mode,traffic,animals,particles,junctions,crossTraffic,police,medians:medianSegments(distance-30,distance+330),roadAt,distance,x,vx,speed,scroll,elapsed,invincible,braking:!!(keys.ArrowDown||keys.s)});}

// Median intervals are in road metres and are shared by rendering and collisions.
function medianGap(at){return Math.max(20,90*Math.pow(.84,Math.floor(Math.max(0,at)/500)))}
function medianSegments(from,to){let result=[];for(let n=Math.max(0,Math.floor(from/180));n<=Math.floor(to/180);n++){let parts=[[n*180+medianGap(n*180),(n+1)*180]];for(let j=Math.max(0,Math.floor((from-324)/400));300+j*400<to+24;j++){const a=300+j*400-24,b=a+48;parts=parts.flatMap(([lo,hi])=>hi<=a||lo>=b?[[lo,hi]]:[[lo,Math.min(hi,a)],[Math.max(lo,b),hi]].filter(([l,h])=>h>l));}result.push(...parts.filter(([a,b])=>b>from&&a<to))}return result}
function enforceMedian(previousX){const half=vehicles[selected].h/17.28;const solid=medianSegments(distance-half,distance+half).length>0;const clearance=vehicles[selected].w/2+7;if(solid&&Math.min(previousX,x)<240+clearance&&Math.max(previousX,x)>240-clearance){x=previousX<240?240-clearance:240+clearance;vx=0;crash();announce('Median barrier — use an opening to cross.')} const r=roadAt(distance),ahead=roadAt(distance+90);$('roadflow').textContent=x<240?'⚠ ONCOMING SIDE':ahead.count<r.count?'⚠ MERGE · '+ahead.count+' LANES AHEAD':r.count+' LANES · '+(solid?'DIVIDED':'OPEN MEDIAN');}
function laneClear(t,lane){const r=roadFor(t);if(lane<0||lane>=r.count||(lane<r.count/2)!==t.oncoming)return false;if(Math.abs(r.centers[lane]-x)<vehicles[selected].w/2+t.v.w/2+18&&Math.abs(t.y-py)<330)return false;return !traffic.some(o=>o!==t&&(o.lane===lane||o.target===lane)&&Math.abs(o.y-t.y)<(t.v.h+o.v.h)/2+230)}
function updateDriver(t,dt){if(t.breakdown)return;t.cooldown=(t.cooldown??5)-dt;t.slowTimer=Math.max(0,(t.slowTimer??0)-dt);
 if(!t.turning&&t.warning<=0&&t.cooldown<=0&&!junctions.some(j=>Math.abs(j.y-t.y)<450)){const r=roadFor(t),candidates=Array.from({length:r.count},(_,i)=>i).filter(i=>i!==t.lane&&(i<r.count/2)===t.oncoming&&Math.abs(i-t.lane)===1);const alternate=candidates[Math.floor(Math.random()*candidates.length)]??-1;const obstruction=traffic.some(o=>o!==t&&o.breakdown&&o.lane===t.lane&&(t.oncoming?o.y-t.y:t.y-o.y)>0&&Math.abs(o.y-t.y)<900);if((obstruction||Math.random()<.65)&&laneClear(t,alternate)){t.target=alternate;t.warning=1.4;}else if(!obstruction&&Math.random()<.55){t.slowTimer=2+Math.random()*2.5;}t.cooldown=5+Math.random()*8;}
 if(t.warning>0){t.warning-=dt;if(t.warning<=0){if(laneClear(t,t.target)){t.turning=1;t.changeFrom=t.x;t.changeProgress=0;}else{t.target=t.lane;t.cooldown=2}}}
 if(t.turning){t.changeProgress+=dt/(t.v.name==='Truck'?2.4:1.6);const u=Math.min(1,t.changeProgress),ease=u*u*(3-2*u);t.x=t.changeFrom+(roadFor(t).centers[t.target]-t.changeFrom)*ease;if(u>=1){t.lane=t.target;t.turning=0}}
}
function updateBreakdowns(){if(distance<nextBreakdown)return;nextBreakdown=distance+240+Math.random()*260;const at=distance+200;if(Math.abs(((at-300)%400+400)%400)<50||Math.abs(((at-300)%400+400)%400)>350)return;const r=roadAt(at);if(r.count===2)return;const lane=Math.floor(Math.random()*r.count);const yy=py-200*8.64;if(traffic.some(t=>Math.abs(t.y-yy)<300&&t.lane===lane))return;traffic.push({x:r.centers[lane],roadCount:r.count,y:yy,lane,target:lane,v:{...(Math.random()<.4?truck:vehicles[2]),color:'#a88c78'},speed:0,cruise:0,oncoming:lane<r.count/2,breakdown:true,warning:0,turning:0,passed:false});announce('Breakdown ahead — watch for hazard lights.');}
